// src/config/strings/formStrings.ts

export const formStrings = {
  formTitleAddContact: 'Προσθήκη Νέας Επαφής', 
  formTitleEditContact: 'Επεξεργασία Επαφής',
  
  nameRequiredError: 'Το όνομα είναι υποχρεωτικό.', 
  nameAndLastNameRequiredError: "Το όνομα και το επώνυμο είναι υποχρεωτικά για φυσικά πρόσωπα.",
  entityNameRequiredError: "Το όνομα της οντότητας/υπηρεσίας είναι υποχρεωτικό.",

  invalidEmailError: "Παρακαλώ εισάγετε μια έγκυρη διεύθυνση email.",
  fieldRequiredError: (fieldName: string) => `Το πεδίο "${fieldName}" είναι υποχρεωτικό.`,
  firstNameRequiredError: "Το όνομα είναι υποχρεωτικό.",
  lastNameRequiredError: "Το επώνυμο είναι υποχρεωτικό.",
  phoneNumberRequiredError: "Ο αριθμός τηλεφώνου είναι υποχρεωτικός.",
  streetRequiredError: "Η οδός είναι υποχρεωτική.",
  cityRequiredError: "Η πόλη είναι υποχρεωτική.",
  postalCodeRequiredError: "Ο ταχυδρομικός κώδικας είναι υποχρεωτικός.",
  countryRequiredError: "Η χώρα είναι υποχρεωτική.",
  socialUrlInvalidError: "Παρακαλώ εισάγετε ένα έγκυρο URL ή αναγνωριστικό.",
  invalidUrlError: "Παρακαλώ εισάγετε ένα έγκυρο URL (π.χ., https://example.com).",
  invalidAfmError: "Το ΑΦΜ πρέπει να αποτελείται από 9 αριθμητικούς χαρακτήρες.",
  mustBeAValidUrl: "Πρέπει να είναι έγκυρο URL (π.χ. https://example.com)",
  mustBeAValidEmail: "Πρέπει να είναι έγκυρη διεύθυνση email",
  mustBeAtLeastChars: (count: number) => `Πρέπει να έχει τουλάχιστον ${count} χαρακτήρες.`,
  mustBeExactlyChars: (count: number) => `Πρέπει να έχει ακριβώς ${count} χαρακτήρες.`,
  mustBeNumeric: "Πρέπει να είναι αριθμός.",
  noteContentRequiredError: 'Το περιεχόμενο της σημείωσης είναι υποχρεωτικό.',
  primaryRequiredError: 'Πρέπει να ορίσετε ένα κύριο στοιχείο.', 

  noteAuthorUserIdRequiredError: "Το User ID του συγγραφέα είναι υποχρεωτικό.",
  noteAuthorDisplayNameRequiredError: "Το εμφανιζόμενο όνομα του συγγραφέα είναι υποχρεωτικό.",
  noteEntityIdRequiredError: "Το ID της οντότητας είναι υποχρεωτικό.",
  noteInvalidCreationDateError: "Μη έγκυρη ημερομηνία δημιουργίας σημείωσης.",
  noteInvalidUpdateDateError: "Μη έγκυρη ημερομηνία ενημέρωσης σημείωσης.",
  noteEmptyTagError: "Τα tags δεν μπορούν να είναι κενά.",
  
  attachmentFileNameRequiredError: "Το όνομα του αρχείου είναι υποχρεωτικό.",
  attachmentFileTypeRequiredError: "Ο τύπος του αρχείου είναι υποχρεωτικός.",
  attachmentFileSizePositiveError: "Το μέγεθος του αρχείου πρέπει να είναι θετικός αριθμός.",
  attachmentFileUrlRequiredError: "Το URL του αρχείου (Data URL) είναι υποχρεωτικό.",
  attachmentInvalidUploadDateError: "Μη έγκυρη ημερομηνία ανεβάσματος συνημμένου.",

  invalidEntityTypeError: "Μη έγκυρος τύπος οντότητας.",
  invalidNoteVisibilityError: "Μη έγκυρη ορατότητα σημείωσης.",
  invalidNoteTypeError: "Μη έγκυρος τύπος σημείωσης.",

  contactTypeLabel: 'Τύπος Επαφής',
  
  firstNameLabel: 'Όνομα',
  firstNamePlaceholder: 'π.χ., Ιωάννης',
  lastNameLabel: 'Επώνυμο',
  lastNamePlaceholder: 'π.χ., Παπαδόπουλος',
  nicknameLabel: 'Χαϊδευτικό/Ψευδώνυμο',
  nicknamePlaceholder: 'π.χ., Γιάννης',
  dateOfBirthLabel: 'Ημερομηνία Γέννησης',
  fatherNameLabel: 'Όνομα Πατρός',
  fatherNamePlaceholder: 'Όνομα πατρός',
  motherNameLabel: 'Όνομα Μητρός',
  motherNamePlaceholder: 'Όνομα μητρός',
  idNumberLabel: 'Αριθμός Δελτίου Ταυτότητας (ΑΔΤ)',
  idNumberPlaceholder: 'π.χ., ΑΙ123456',
  issuingAuthorityLabel: 'Αρχή Έκδοσης ΑΔΤ',
  issuingAuthorityPlaceholder: 'π.χ., Τ.Α. Μενεμένης',
  dateOfIssueLabel: 'Ημερομηνία Έκδοσης ΑΔΤ',
  placeOfBirthLabel: 'Τόπος Γέννησης',
  placeOfBirthPlaceholder: 'π.χ., Θεσσαλονίκη',
  maritalStatusLabel: 'Οικογενειακή Κατάσταση',
  
  entityNameLabel: 'Επωνυμία / Όνομα Υπηρεσίας',
  entityNamePlaceholder: 'π.χ., Εταιρεία Α.Ε. ή Πολεοδομία Αθηνών',

  brandNameLabel: 'Εμπορική Επωνυμία / Διακριτικός Τίτλος',
  brandNamePlaceholder: 'π.χ., "Το Καλύτερο Προϊόν"',
  companyTypeLabel: 'Τύπος Εταιρείας',
  companyTypePlaceholder: 'π.χ., Α.Ε., Ε.Π.Ε., Ι.Κ.Ε.',
  gemhNumberLabel: 'Αριθμός Γ.Ε.ΜΗ.',
  gemhNumberPlaceholder: '1234567890123',
  parentCompanyLabel: 'Όνομα Ομίλου/Μητρικής Εταιρείας',
  parentCompanyPlaceholder: 'π.χ. Όμιλος Εταιρειών XYZ',

  serviceTypeLabel: 'Τύπος Υπηρεσίας',
  serviceTypePlaceholder: 'π.χ., Πολεοδομία, ΔΟΥ',
  directorateLabel: 'Διεύθυνση (Υπηρεσίας)',
  directoratePlaceholder: 'π.χ., Διεύθυνση Πολεοδομίας',
  departmentLabel: 'Τμήμα (Υπηρεσίας)',
  departmentPlaceholder: 'π.χ., Τμήμα Έκδοσης Αδειών',

  professionLabel: 'Επάγγελμα',
  professionPlaceholder: 'π.χ., Αρχιτέκτονας, Δικηγόρος',
  employmentStatusLabel: 'Κατάσταση Απασχόλησης',
  worksAtCompanyLabel: 'Εταιρεία Εργασίας',
  worksAtCompanyPlaceholder: 'π.χ., ABC Constructions AE',
  jobTitleLabel: 'Θέση Εργασίας',
  jobTitlePlaceholder: 'π.χ., Μηχανικός Εργοταξίου',
  educationLevelLabel: 'Επίπεδο Μόρφωσης',
  educationLevelPlaceholder: 'π.χ., Πτυχίο ΑΕΙ, Μεταπτυχιακό',
  
  propertyAttributesLabel: 'Ιδιότητες Ακινήτων',
  isPropertyOwnerLabel: 'Ιδιοκτήτης Ακινήτου',
  isLandParcelOwnerLabel: 'Οικοπεδούχος',
  isTenantLabel: 'Ενοικιαστής',
  isProspectiveBuyerLabel: 'Ενδιαφέρεται για Αγορά',
  isProspectiveSellerLabel: 'Ενδιαφέρεται για Πώληση',

  afmLabel: 'ΑΦΜ',
  afmPlaceholder: 'Αριθμός Φορολογικού Μητρώου',
  doyLabel: 'ΔΟΥ',
  doyPlaceholder: 'Δημόσια Οικονομική Υπηρεσία',
  rolesLabel: 'Ρόλοι (διαχωρισμένοι με κόμμα)',
  rolesPlaceholder: 'π.χ., buyer,employee (αγγλικές λέξεις-κλειδιά)',
  emailLabel: 'Email',
  emailPlaceholder: 'contact@example.gr',
  phoneLabel: 'Τηλέφωνο', 
  phoneNumbersLabel: 'Τηλεφωνικοί Αριθμοί',
  addPhoneNumberButton: 'Προσθήκη Τηλεφώνου', 
  removePhoneNumberButton: 'Αφαίρεση Τηλεφώνου',
  phoneNumberLabel: 'Αριθμός',
  phoneNumberPlaceholder: 'π.χ., 2101234567 ή 69xxxxxxxx',
  phoneTypeLabel: 'Τύπος Τηλεφώνου',
  phoneIsPrimaryLabel: 'Κύριο Τηλέφωνο',
  phoneNotesLabel: 'Σημειώσεις Τηλεφώνου',
  phoneNotesPlaceholder: 'π.χ., Μόνο για Viber',
  phoneLabelLabel: 'Ετικέτα Τηλεφώνου',
  phoneLabelPlaceholder: 'π.χ., Γραμματεία, Κινητό Γιώργου',
  countryCodeLabel: 'Κωδικός Χώρας',
  countryCodePlaceholder: '+30',
  extensionLabel: 'Εσωτερικό',
  extensionPlaceholder: 'π.χ., 101',
  protocolsLabel: 'Πρωτόκολλα Επικοινωνίας',
  
  voipIntegrationSectionTitle: 'Ενσωμάτωση VoIP',
  voipSystemNameLabel: 'Όνομα Συστήματος VoIP',
  voipSystemNamePlaceholder: 'π.χ., Asterisk, 3CX',
  voipSystemSpecificIdLabel: 'ID Συστήματος VoIP',
  voipSystemSpecificIdPlaceholder: 'Αναγνωριστικό στο σύστημα VoIP',
  voipCanDialLabel: 'Δυνατότητα Κλήσης μέσω Συστήματος',

  avatarUrlLabel: 'URL Εικόνας/Λογοτύπου',
  avatarUrlPlaceholder: 'https://example.com/logo.png',
  notesLabel: 'Σημειώσεις', 
  notesPlaceholder: 'Πρόσθετες σημειώσεις...', 
  newNotePlaceholder: 'Πληκτρολογήστε τη σημείωσή σας...',
  addNoteButton: 'Προσθήκη Σημείωσης',
  noteTypeLabel: 'Τύπος Σημείωσης', 
  noteVisibilityLabel: 'Ορατότητα Σημείωσης', 
  
  socialMediaLabel: 'Κοινωνικά Δίκτυα & Messaging',
  socialMediaPlaceholder: 'π.χ., facebook:https://facebook.com/username\nwhatsapp:6900000000\nwebsite:https://example.com',
  addSocialMediaButton: 'Προσθήκη Social Media/Link', 
  socialPlatformLabel: 'Πλατφόρμα',
  socialUrlLabel: 'Link/Username/Αριθμός',
  socialUrlPlaceholder: 'https://..., @username, 69xxxxxxxx',

  addressesLabel: 'Διευθύνσεις',
  addAddressButton: 'Προσθήκη Διεύθυνσης', 
  removeAddressButton: 'Αφαίρεση Διεύθυνσης',
  addressStreetLabel: 'Οδός',
  addressStreetPlaceholder: 'π.χ., Ερμού',
  addressNumberLabel: 'Αριθμός',
  addressNumberPlaceholder: 'π.χ., 10Α',
  addressAreaLabel: 'Περιοχή',
  addressAreaPlaceholder: 'π.χ., Κολωνάκι',
  addressMunicipalityLabel: 'Δήμος',
  addressMunicipalityPlaceholder: 'π.χ., Αθηναίων',
  addressCityLabel: 'Πόλη',
  addressCityPlaceholder: 'π.χ., Αθήνα',
  addressPrefectureLabel: 'Νομός',
  addressPrefecturePlaceholder: 'π.χ., Αττικής',
  addressCountryLabel: 'Χώρα',
  addressCountryPlaceholder: 'π.χ., Ελλάδα',
  addressPostalCodeLabel: 'Τ.Κ.',
  addressPostalCodePlaceholder: 'π.χ., 10563',
  addressTypeLabel: 'Τύπος Διεύθυνσης',
  addressIsPrimaryLabel: 'Κύρια Διεύθυνση',

  showPasswordButtonLabel: "Εμφάνιση κωδικού",
  hidePasswordButtonLabel: "Απόκρυψη κωδικού",

  incrementButtonLabel: "Αύξηση",
  decrementButtonLabel: "Μείωση",

  addAttachmentsButton: "Προσθήκη Συνημμένων",
  maxFileSizeError: (maxSizeMB: number) => `Το συνολικό μέγεθος των αρχείων δεν πρέπει να υπερβαίνει τα ${maxSizeMB}MB.`,
  maxFilesError: (maxFiles: number) => `Μπορείτε να επισυνάψετε έως ${maxFiles} αρχεία.`,
  fileTypeError: "Ο τύπος ενός ή περισσοτέρων αρχείων δεν υποστηρίζεται.",
  fileReadError: "Σφάλμα κατά την ανάγνωση ενός αρχείου.",
  selectedFilesTitle: "Επιλεγμένα Αρχεία:",
  noFilesSelected: "Δεν έχουν επιλεγεί αρχεία.",
  removeButtonAriaLabel: (fileName: string) => `Αφαίρεση αρχείου ${fileName}`,

  // Activity Form Strings
  activityTitleLabel: "Τίτλος Ενέργειας",
  activityCategoryLabel: "Κατηγορία Ενέργειας",
  activitySpecificTypeLabel: "Εξειδικευμένος Τύπος",
  descriptionLabel: "Περιγραφή",
  startTimeLabel: "Ώρα Έναρξης",
  endTimeLabel: "Ώρα Λήξης",
  activityOutcomeLabel: "Αποτέλεσμα",
  relatedEntitiesLabel: "Συσχετιζόμενες Οντότητες",
  relatedContactLabel: "Σχετική Επαφή (ID)",
  relatedProjectLabel: "Σχετικό Έργο (ID)",
  relatedPropertyLabel: "Σχετικό Ακίνητο (ID)",
  relatedDealLabel: "Σχετική Ευκαιρία (ID)",
  saveActivityButton: "Αποθήκευση Ενέργειας",
  activityFormErrorRequired: (fieldName: string) => `Το πεδίο "${fieldName}" είναι υποχρεωτικό για την ενέργεια.`,
  activityFormErrorInvalidDate: "Μη έγκυρη ημερομηνία/ώρα.",
  activityFormErrorEndTimeBeforeStart: "Η ώρα λήξης δεν μπορεί να είναι πριν την ώρα έναρξης.",
  
  // Document Form Strings
  documentCategoryLabel: "Κατηγορία Εγγράφου",
  tagsLabel: "Ετικέτες (χωρισμένες με κόμμα)",
};